"use client";

import React, { useEffect, useState } from "react";
import Modal from "../Modal";
import TableToolbar from "../TableToolbar";
import TablePagination from "../TablePagination";
import TableRowActions from "../TableRowActions";
import StatCard from "../StatCard";
import FormField, { FormActionButtons, RequiredFieldsNote } from "../FormField";
import ConfirmDialog from "../ConfirmDialog";
import StatusToggle from "../StatusToggle";
import { usePaginatedList } from "../../hooks/usePaginatedList";
import { useFormValidation } from "../../hooks/useFormValidation";
import { API_URL } from "../../lib/api";
import { authHeaders } from "../../lib/auth";
import { readApiError } from "../../lib/apiError";
import { toast } from "../../lib/toast";
import { USER_STATUS_FILTER_OPTIONS, filterCatalogTable } from "../../lib/dashboard/constants";
import { validateCatalogName } from "../../lib/validation";

export interface CatalogItemBase {
  _id: string;
  name: string;
  isActive: boolean;
}

export interface CatalogSecondaryField {
  key: "label" | "code" | "currency";
  createLabel: string;
  editLabel: string;
  placeholder?: string;
  required?: boolean;
  mono?: boolean;
  /** Backend assigns value — hide input on create and omit from POST body */
  autoGenerated?: boolean;
  /** Show value on edit but do not allow changes / omit from PUT body */
  readOnly?: boolean;
  hint?: string;
  validate?: (value: string) => string;
  getValue: (item: CatalogItemBase & Record<string, unknown>) => string;
  toBodyValue?: (value: string) => string;
}

export interface CatalogAdminConfig {
  endpoint: "categories" | "projects" | "countries";
  singular: string;
  plural: string;
  totalStatTitle: string;
  totalStatSubtext: string;
  totalEmoji: string;
  activeSubtext: string;
  searchPlaceholder: string;
  emptyTitle: string;
  emptyHint?: string;
  nameCreateLabel: string;
  namePlaceholder: string;
  nameValidateLabel: string;
  secondary: CatalogSecondaryField;
}

type FormFieldKey = "name" | "secondary";

interface CatalogAdminPanelProps {
  config: CatalogAdminConfig;
  onCatalogChanged?: () => void;
  openCreateSignal?: number;
}

export default function CatalogAdminPanel({
  config,
  onCatalogChanged,
  openCreateSignal = 0,
}: CatalogAdminPanelProps) {
  type Item = CatalogItemBase & Record<string, unknown>;

  const [items, setItems] = useState<Item[]>([]);
  const [loading, setLoading] = useState(false);
  const [showCreate, setShowCreate] = useState(false);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [selected, setSelected] = useState<Item | null>(null);
  const [modalType, setModalType] = useState<"view" | "edit" | null>(null);

  const [newName, setNewName] = useState("");
  const [newSecondary, setNewSecondary] = useState("");
  const [editName, setEditName] = useState("");
  const [editSecondary, setEditSecondary] = useState("");
  const [editActive, setEditActive] = useState(true);

  const createForm = useFormValidation<FormFieldKey>();
  const editForm = useFormValidation<FormFieldKey>();
  const table = usePaginatedList(items, {
    filterFn: filterCatalogTable,
    initialFilters: { status: "ALL" },
  });

  const fetchItems = async () => {
    setLoading(true);
    try {
      const res = await fetch(`${API_URL}/${config.endpoint}`, { headers: authHeaders() });
      if (res.ok) setItems(await res.json());
    } catch {
      toast.error(`Failed to load ${config.plural.toLowerCase()}`);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void fetchItems();
  }, [config.endpoint]);

  useEffect(() => {
    if (openCreateSignal > 0) {
      closeCreate();
      setShowCreate(true);
    }
  }, [openCreateSignal]);

  const closeCreate = () => {
    setShowCreate(false);
    setNewName("");
    setNewSecondary("");
    createForm.clearAll();
  };

  const secondaryIsAuto = Boolean(config.secondary.autoGenerated);
  const secondaryIsReadOnly = Boolean(config.secondary.readOnly || config.secondary.autoGenerated);

  const secondaryBody = (value: string) => {
    if (secondaryIsAuto || !config.secondary.toBodyValue) return {};
    return {
      [config.secondary.key]: config.secondary.toBodyValue(value),
    };
  };

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    const validators: Partial<Record<FormFieldKey, () => string>> = {
      name: () => validateCatalogName(newName, config.nameValidateLabel),
    };
    if (!secondaryIsAuto && config.secondary.validate) {
      validators.secondary = () => config.secondary.validate!(newSecondary);
    }
    const ok = createForm.validateAll(validators);
    if (!ok) {
      createForm.focusFirstInvalid();
      return;
    }
    try {
      const res = await fetch(`${API_URL}/${config.endpoint}`, {
        method: "POST",
        headers: authHeaders() as HeadersInit,
        body: JSON.stringify({
          name: newName.trim(),
          ...secondaryBody(newSecondary),
        }),
      });
      if (!res.ok) {
        throw new Error(await readApiError(res, `Failed to create ${config.singular.toLowerCase()}`));
      }
      closeCreate();
      toast.success(`${config.singular} created successfully!`);
      await fetchItems();
      onCatalogChanged?.();
    } catch (err: any) {
      toast.error(err.message || `Failed to create ${config.singular.toLowerCase()}`);
    }
  };

  const handleDelete = async (id: string) => {
    try {
      const res = await fetch(`${API_URL}/${config.endpoint}/${id}`, {
        method: "DELETE",
        headers: authHeaders() as HeadersInit,
      });
      if (!res.ok) {
        throw new Error(await readApiError(res, `Failed to delete ${config.singular.toLowerCase()}`));
      }
      setDeleteId(null);
      toast.success(`${config.singular} deleted.`);
      await fetchItems();
      onCatalogChanged?.();
    } catch (err: any) {
      toast.error(err.message || `Failed to delete ${config.singular.toLowerCase()}`);
    }
  };

  const handleToggle = async (item: Item) => {
    try {
      const res = await fetch(`${API_URL}/${config.endpoint}/${item._id}`, {
        method: "PUT",
        headers: authHeaders() as HeadersInit,
        body: JSON.stringify({ isActive: !item.isActive }),
      });
      if (!res.ok) {
        throw new Error(await readApiError(res, `Failed to update ${config.singular.toLowerCase()}`));
      }
      await fetchItems();
      onCatalogChanged?.();
    } catch (err: any) {
      toast.error(err.message || `Failed to update ${config.singular.toLowerCase()}`);
    }
  };

  const openEdit = (item: Item) => {
    setSelected(item);
    setModalType("edit");
    setEditName(item.name);
    setEditSecondary(config.secondary.getValue(item));
    setEditActive(item.isActive);
    editForm.clearAll();
  };

  const handleUpdate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selected) return;
    const validators: Partial<Record<FormFieldKey, () => string>> = {
      name: () => validateCatalogName(editName, config.nameValidateLabel),
    };
    if (!secondaryIsReadOnly && config.secondary.validate) {
      validators.secondary = () => config.secondary.validate!(editSecondary);
    }
    const ok = editForm.validateAll(validators);
    if (!ok) {
      editForm.focusFirstInvalid();
      return;
    }
    try {
      const res = await fetch(`${API_URL}/${config.endpoint}/${selected._id}`, {
        method: "PUT",
        headers: authHeaders() as HeadersInit,
        body: JSON.stringify({
          name: editName.trim(),
          ...(secondaryIsReadOnly ? {} : secondaryBody(editSecondary)),
          isActive: editActive,
        }),
      });
      if (!res.ok) {
        throw new Error(await readApiError(res, `Failed to update ${config.singular.toLowerCase()}`));
      }
      setModalType(null);
      setSelected(null);
      editForm.clearAll();
      toast.success(`${config.singular} updated successfully!`);
      await fetchItems();
      onCatalogChanged?.();
    } catch (err: any) {
      toast.error(err.message || `Failed to update ${config.singular.toLowerCase()}`);
    }
  };

  const activeCount = items.filter((c) => c.isActive).length;
  const secondaryHeader =
    config.secondary.key === "label"
      ? "Label"
      : config.secondary.key === "currency"
        ? "Currency"
        : "Code";

  return (
    <div className="mt-2">
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 sm:gap-4 mb-6 sm:mb-8">
        <StatCard
          title={config.totalStatTitle}
          value={String(items.length)}
          subtext={config.totalStatSubtext}
          emoji={config.totalEmoji}
        />
        <StatCard
          title="Active"
          value={String(activeCount)}
          subtext={config.activeSubtext}
          emoji="✅"
          valueColor="text-emerald-600"
        />
        <StatCard
          title="Inactive"
          value={String(items.length - activeCount)}
          subtext="Hidden from form"
          emoji="○"
          valueColor="text-rose-500"
        />
      </div>

      <div className="flex items-center justify-end mb-4">
        <button
          type="button"
          onClick={() => {
            closeCreate();
            setShowCreate(true);
          }}
          className="px-4 py-2 rounded-lg bg-[var(--af-navy)] hover:bg-[var(--af-navy-soft)] text-xs font-bold text-white transition-colors cursor-pointer"
        >
          + Add {config.singular}
        </button>
      </div>

      {loading ? (
        <div className="text-center py-12 text-slate-700">
          Loading {config.plural.toLowerCase()}...
        </div>
      ) : (
        <div className="portal-card rounded-2xl shadow-xl p-4 sm:p-6 md:p-8 min-w-0">
          <div className="mb-4">
            <TableToolbar
              search={table.search}
              onSearchChange={table.setSearch}
              searchPlaceholder={config.searchPlaceholder}
              filters={[
                {
                  id: "status",
                  value: table.filters.status,
                  onChange: (value) => table.setFilter("status", value),
                  options: USER_STATUS_FILTER_OPTIONS,
                },
              ]}
            />
          </div>

          {table.totalCount === 0 ? (
            <div className="text-center py-12 text-slate-700">
              <p className="text-sm font-semibold">{config.emptyTitle}</p>
              {config.emptyHint && <p className="text-xs mt-1">{config.emptyHint}</p>}
            </div>
          ) : (
            <>
              <div className="af-table-wrap">
                <table className="af-table min-w-full">
                  <thead>
                    <tr>
                      <th className="py-3 px-4">Name</th>
                      <th className="py-3 px-4">{secondaryHeader}</th>
                      <th className="py-3 px-4">Status</th>
                      <th className="py-3 px-4">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {table.paginated.map((item) => {
                      const secondaryValue = config.secondary.getValue(item);
                      return (
                        <tr key={item._id} className="hover:bg-slate-50 transition-colors">
                          <td className="py-3.5 px-4 font-semibold text-slate-900">{item.name}</td>
                          <td
                            className={`py-3.5 px-4 text-slate-700 ${
                              config.secondary.mono ? "font-mono text-xs" : ""
                            }`}
                          >
                            {secondaryValue || "—"}
                          </td>
                          <td className="py-3.5 px-4">
                            <StatusToggle
                              isActive={item.isActive}
                              onToggle={() => handleToggle(item)}
                            />
                          </td>
                          <td className="py-3.5 px-4">
                            <TableRowActions
                              align="start"                              onView={() => {
                                setSelected(item);
                                setModalType("view");
                              }}
                              onEdit={() => openEdit(item)}
                              onDelete={() => setDeleteId(item._id)}
                            />
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
              <TablePagination
                page={table.page}
                totalPages={table.totalPages}
                pageSize={table.pageSize}
                totalCount={table.totalCount}
                onPageChange={table.setPage}
                onPageSizeChange={table.setPageSize}
              />
            </>
          )}
        </div>
      )}

      <ConfirmDialog
        open={!!deleteId}
        title={`Delete ${config.singular}?`}
        onCancel={() => setDeleteId(null)}
        onConfirm={() => deleteId && handleDelete(deleteId)}
      />

      <Modal
        isOpen={showCreate}
        onClose={closeCreate}
        title={`Create ${config.singular}`}
        maxWidthClass="max-w-lg"
      >
        <form
          onSubmit={handleCreate}
          noValidate
          className={
            secondaryIsAuto
              ? "grid grid-cols-1 gap-4"
              : "grid grid-cols-1 sm:grid-cols-2 gap-4"
          }
        >
          <RequiredFieldsNote className={secondaryIsAuto ? "-mt-1" : "sm:col-span-2 -mt-1"} />
          <FormField
            label={config.nameCreateLabel}
            required
            error={createForm.errors.name}
          >
            <input
              value={newName}
              onChange={(e) => {
                setNewName(e.target.value);
                createForm.clearError("name");
              }}
              onBlur={() =>
                createForm.onBlur(
                  "name",
                  validateCatalogName(newName, config.nameValidateLabel)
                )
              }
              placeholder={config.namePlaceholder}
              className={createForm.fieldClass("af-input", "name")}
              aria-invalid={Boolean(createForm.errors.name)}
            />
          </FormField>
          {!secondaryIsAuto && (
            <FormField
              label={config.secondary.createLabel}
              required={config.secondary.required}
              error={createForm.errors.secondary}
            >
              <input
                value={newSecondary}
                onChange={(e) => {
                  setNewSecondary(e.target.value);
                  createForm.clearError("secondary");
                }}
                onBlur={() =>
                  createForm.onBlur(
                    "secondary",
                    config.secondary.validate?.(newSecondary) || ""
                  )
                }
                placeholder={config.secondary.placeholder}
                className={createForm.fieldClass("af-input", "secondary")}
                aria-invalid={Boolean(createForm.errors.secondary)}
              />
            </FormField>
          )}
          {secondaryIsAuto && config.secondary.hint && (
            <p className="text-xs text-slate-600 -mt-1">{config.secondary.hint}</p>
          )}
          <div className={secondaryIsAuto ? undefined : "sm:col-span-2"}>
            <FormActionButtons
              onCancel={closeCreate}
              submitLabel={`Create ${config.singular}`}
            />
          </div>
        </form>
      </Modal>

      <Modal
        isOpen={!!selected && modalType === "view"}
        onClose={() => {
          setSelected(null);
          setModalType(null);
        }}
        title={`${config.singular} Details`}
        maxWidthClass="max-w-md"
      >
        {selected && (
          <div className="space-y-3 text-sm">
            <div className="flex justify-between gap-4">
              <span className="text-slate-700">Name</span>
              <span className="font-semibold text-slate-900">{selected.name}</span>
            </div>
            <div className="flex justify-between gap-4">
              <span className="text-slate-700">{secondaryHeader}</span>
              <span
                className={`text-slate-600 text-right ${
                  config.secondary.mono ? "font-mono" : ""
                }`}
              >
                {config.secondary.getValue(selected) || "—"}
              </span>
            </div>
            <div className="flex justify-between gap-4">
              <span className="text-slate-700">Status</span>
              <span className={selected.isActive ? "text-emerald-600" : "text-rose-600"}>
                {selected.isActive ? "Active" : "Inactive"}
              </span>
            </div>
            <div className="flex justify-end pt-2">
              <button
                type="button"
                onClick={() => {
                  setSelected(null);
                  setModalType(null);
                }}
                className="px-4 py-2 rounded-lg bg-slate-100 hover:bg-slate-200 text-xs font-semibold text-slate-600 transition-colors cursor-pointer"
              >
                Close
              </button>
            </div>
          </div>
        )}
      </Modal>

      <Modal
        isOpen={!!selected && modalType === "edit"}
        onClose={() => {
          setSelected(null);
          setModalType(null);
          editForm.clearAll();
        }}
        title={`Edit ${config.singular}`}
        maxWidthClass="max-w-lg"
      >
        {selected && (
          <form onSubmit={handleUpdate} noValidate className="space-y-4">
            <FormField label="Name" required error={editForm.errors.name}>
              <input
                value={editName}
                onChange={(e) => {
                  setEditName(e.target.value);
                  editForm.clearError("name");
                }}
                onBlur={() =>
                  editForm.onBlur(
                    "name",
                    validateCatalogName(editName, config.nameValidateLabel)
                  )
                }
                className={editForm.fieldClass("af-input", "name")}
                aria-invalid={Boolean(editForm.errors.name)}
              />
            </FormField>
            <FormField
              label={config.secondary.editLabel}
              required={secondaryIsReadOnly ? false : config.secondary.required}
              error={secondaryIsReadOnly ? undefined : editForm.errors.secondary}
              hint={
                secondaryIsReadOnly
                  ? "Assigned automatically and cannot be changed."
                  : config.secondary.hint
              }
            >
              <input
                value={editSecondary}
                readOnly={secondaryIsReadOnly}
                disabled={secondaryIsReadOnly}
                onChange={
                  secondaryIsReadOnly
                    ? undefined
                    : (e) => {
                        setEditSecondary(e.target.value);
                        editForm.clearError("secondary");
                      }
                }
                onBlur={
                  secondaryIsReadOnly
                    ? undefined
                    : () =>
                        editForm.onBlur(
                          "secondary",
                          config.secondary.validate?.(editSecondary) || ""
                        )
                }
                className={
                  secondaryIsReadOnly
                    ? `af-input ${config.secondary.mono ? "font-mono text-xs" : ""} bg-slate-50 text-slate-600 cursor-not-allowed`
                    : editForm.fieldClass("af-input", "secondary")
                }
                aria-invalid={
                  secondaryIsReadOnly ? undefined : Boolean(editForm.errors.secondary)
                }
              />
            </FormField>
            <FormField label="Status">
              <select
                value={editActive ? "ACTIVE" : "INACTIVE"}
                onChange={(e) => setEditActive(e.target.value === "ACTIVE")}
                className="af-select"
              >
                <option value="ACTIVE">Active</option>
                <option value="INACTIVE">Inactive</option>
              </select>
            </FormField>
            <FormActionButtons
              onCancel={() => {
                setSelected(null);
                setModalType(null);
                editForm.clearAll();
              }}
              submitLabel="Save Changes"
            />
          </form>
        )}
      </Modal>
    </div>
  );
}
