"use client";

import CatalogAdminPanel, { CatalogAdminConfig } from "./CatalogAdminPanel";

const PROJECTS_CONFIG: CatalogAdminConfig = {
  endpoint: "projects",
  singular: "Project",
  plural: "Projects",
  totalStatTitle: "Total Projects",
  totalStatSubtext: "Configured projects",
  totalEmoji: "📁",
  activeSubtext: "Selectable on form",
  searchPlaceholder: "Search name or code...",
  emptyTitle: "No projects yet",
  emptyHint: "Add a project so requesters can select it on the expense form.",
  nameCreateLabel: "Project Name",
  namePlaceholder: "Aceolution Portal",
  nameValidateLabel: "Project name",
  secondary: {
    key: "code",
    createLabel: "Code",
    editLabel: "Code",
    mono: true,
    autoGenerated: true,
    readOnly: true,
    hint: "Code is assigned automatically (e.g. ACE-PR-000001) and is unique.",
    getValue: (item) => String(item.code ?? ""),
  },
};

interface ProjectsPanelProps {
  onCatalogChanged?: () => void;
  openCreateSignal?: number;
}

export default function ProjectsPanel(props: ProjectsPanelProps) {
  return <CatalogAdminPanel config={PROJECTS_CONFIG} {...props} />;
}
